### ISSUE TITLE
Please add a good README.txt file

### ISSUE THREAD

**Issue by dusto2020** [Teom-Enterprise/teom#2]
@alexsrka you have to add a README.txt file for a promotion

**Comment by alxsrk** [comment]
> @alexsrka you have to add a README.txt file for a promotion

Do you mean a **README.MD**?
Never heard about README.txt.

**Comment by alxsrk** [comment]
And who is @alexsrka?

**Comment by alxsrk** [comment]
### Closed due to insufficient information
Reopening in the future is not excluded.
